# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: microdrop.droplet-planning-plugin
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    - flatland-fork
    - flatland-helpers
    - microdrop-plugin-manager >=0.11
    - pandas
    - path_helpers >=0.2.post4
    - pandas-helpers
    - paho-mqtt-helpers >=0.2
    - si-prefix

  run:
    - flatland-fork
    - flatland-helpers
    - pandas
    - path_helpers >=0.2.post4
    - pandas-helpers
    - paho-mqtt-helpers >=0.2
    - si-prefix

about:
  home: https://github.com/Lucaszw/droplet-planning-plugin
  license: GPL
